on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  converge:
    name: Skaffold Build To Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cp .env-production .env

      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get -y install buildah

      - name: Build and Push Image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          CACHE_REPO: ghcr.io/${{ github.repository }}/cache
        run: |
          buildah bud \
            --format docker \
            -f Dockerfile \
            --layers \
            --cache-from $CACHE_REPO \
            --cache-to $CACHE_REPO \
            -t $IMAGE \
            .

      - name: Push Image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: buildah push $IMAGE

  deploy:
    name: Deploy
    needs: converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ConfigCreate
        run: |
          mkdir ~/.kube/
          echo "${{ secrets.KUBERCONFIG }}" | base64 -d > config
          mv config ~/.kube/
          helm upgrade -i --kubeconfig ~/.kube/config "webclient" ".helm" --set global.IngressDomain=rarimo.com --set "image.repository=ghcr.io/${GITHUB_REPOSITORY}" --set "image.tag=${GITHUB_REF_NAME}" --create-namespace --namespace landing-prod
